{{ config(materialized='table') }}

select distinct location, Island,Total_recovered,total_cases_per_million
,TOTAL_ACTIVE_CASES
NEW_CASES_PER_MILLION,
NEW_RECOVERED,
CASE_FATALITY_RATE,
NEW_DEATHS
,NEW_CASES,
TOTAL_DEATHS
,"DATE",
CASE_RECOVERED_RATE
,NEW_ACTIVE_CASES
TOTAL_CASES
,TOTAL_DEATHS_PER_MILLION
GROWTH_FACTOR_OF_NEW_CASES,
AREA_KM_2_,
TOTAL_RURAL_VILLAGES
,TOTAL_REGENCIES
,POPULATION_DENSITY
,POPULATION
,TOTAL_CITIES
,TOTAL_DISTRICTS
,TOTAL_URBAN_VILLAGES
from "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_HARI_KRISHNA"